'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PCFServiceModel
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IPCFService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PCFService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CallAisResultOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ConsCallPcf.My.MySettings.Default.ConsCallPcf_PCFServiceModel_PCFService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CallAisResultCompleted As CallAisResultCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPCFService/CallAisResult", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallAisResult(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Token As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ILAPIParam As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal PolNum As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef result As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("CallAisResult", New Object() {Token, ILAPIParam, PolNum, result})
            result = CType(results(1),String)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallAisResultAsync(ByVal Token As String, ByVal ILAPIParam As String, ByVal PolNum As String, ByVal result As String)
            Me.CallAisResultAsync(Token, ILAPIParam, PolNum, result, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallAisResultAsync(ByVal Token As String, ByVal ILAPIParam As String, ByVal PolNum As String, ByVal result As String, ByVal userState As Object)
            If (Me.CallAisResultOperationCompleted Is Nothing) Then
                Me.CallAisResultOperationCompleted = AddressOf Me.OnCallAisResultOperationCompleted
            End If
            Me.InvokeAsync("CallAisResult", New Object() {Token, ILAPIParam, PolNum, result}, Me.CallAisResultOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallAisResultOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallAisResultCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallAisResultCompleted(Me, New CallAisResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessErrors
        
        Private errorListField() As BusinessErrorVo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ErrorList() As BusinessErrorVo()
            Get
                Return Me.errorListField
            End Get
            Set
                Me.errorListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BusinessWarningVo)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessErrorVo
        
        Private errorCodeField As String
        
        Private errorFieldField As String
        
        Private errorMessagesField() As ArrayOfKeyValueOfstringstringKeyValueOfstringstring
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorField() As String
            Get
                Return Me.errorFieldField
            End Get
            Set
                Me.errorFieldField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)>  _
        Public Property ErrorMessages() As ArrayOfKeyValueOfstringstringKeyValueOfstringstring()
            Get
                Return Me.errorMessagesField
            End Get
            Set
                Me.errorMessagesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Partial Public Class ArrayOfKeyValueOfstringstringKeyValueOfstringstring
        
        Private keyField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessWarningVo
        Inherits BusinessErrorVo
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub CallAisResultCompletedEventHandler(ByVal sender As Object, ByVal e As CallAisResultCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallAisResultCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        'Public Overloads ReadOnly Property Result() As BusinessErrors
        '    Get
        '        Me.RaiseExceptionIfNecessary
        '        Return CType(Me.results(0),BusinessErrors)
        '    End Get
        'End Property

        '''<remarks/>
        Public Overloads ReadOnly Property result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
